### ISSUE TITLE
fetchCompleted function fails due to inconsistent API response

### ISSUE THREAD

**Issue by kashiashvili** [darekkay/todoist-export#23]
The fetchCompleted function in app.js currently assumes that the Todoist API will always return exactly 200 items per page. This is used to determine when to stop the recursive fetching of pages. However, it appears that the API is not consistently returning 200 items, with responses varying between 180-200 items. This inconsistency is causing the recursion to stop prematurely, leading to incomplete data.

I understand that this is primarily an issue with the Todoist API, and I have opened a support ticket with them. However, given the uncertainty of when or if this will be resolved on their end, I'm wondering if we could implement a temporary workaround to handle this inconsistency.

One solution I thought of is to check if items length is more than 0 instead of equal to COMPL_MAX_PAGE_SIZE.

I would love to hear better solutions. 

https://github.com/darekkay/todoist-export/blob/d17249fb693b9b4becd9077d58e2c170848f92b1/src/app.js#L210

Also, API does not seem to be returning an error response when there are no items left, it just returns an empty array, I might be missing something here.

https://github.com/darekkay/todoist-export/blob/d17249fb693b9b4becd9077d58e2c170848f92b1/src/app.js#L192

Thank you for your attention to this matter.

**Comment by darekkay** [comment]
Thank you very much for the report and the detailed debugging! I could reproduce what you wrote. The suggested solution will lead to one more call than before, but I don't see any other reliable way, either. Lowering the pagination size might solve it, but it would lead to a higher number of total calls.

This has been fixed in f3527a0cd0b5ace1d62f8eb499560a466215d02b and is already available on the live page.
