### ISSUE TITLE
Fetch completed items with all the data

### ISSUE THREAD

**Issue by kashiashvili** [darekkay/todoist-export#24]
I'm currently working on a free open-source Todoist analytics dashboard app. I want to let people export data using this tool and import it into my app. However, the fetchCompleted function in app.js does not include the annotate_items=true parameter in the API call to completed/get_all. This parameter is necessary to fetch all the data associated with each item.

https://github.com/darekkay/todoist-export/blob/d17249fb693b9b4becd9077d58e2c170848f92b1/src/app.js#L186

Can we add the parameter? I wanted to check if there are any potential issues or side effects I might be missing.

**Comment by darekkay** [comment]
Thank you, I've either missed those options or they came after the initial implementation. I've included both `annotate_items` and `annotate_notes`. This makes the result (for me) almost 4 times as big and probably makes the export time even longer, but as a user I expect the export to be complete.

Fixed in 02f7e6a4fb169129e778b3478656ef51c78e0605 and available on the live page.
